name: Build

on: [push]

jobs:
  build:
    name: Compilar aplicación React
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Instalar dependencias
        run: npm install
        working-directory: ./

      - name: Compilar aplicación
        run: npm run build
        working-directory: ./
