name: Mediatech CI

on: [push]

jobs:
  lint:
    name: Ejecutar Linter
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Instalar dependencias
        run: npm install
        working-directory: ./

      - name: Ejecutar lint
        run: npm run lint
        working-directory: ./

  test:
    name: Ejecutar Tests
    runs-on: [self-hosted]
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Instalar dependencias
        run: npm install
        working-directory: ./

      - name: Ejecutar tests
        run: npm run test
        working-directory: ./

  build:
    name: Compilar aplicación
    runs-on: [self-hosted]
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Instalar dependencias
        run: npm install
        working-directory: ./

      - name: Compilar React App
        run: npm run build
        working-directory: ./
